# R packages for fresh installation

install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")

cran_pkgs <- c(
  "tidyverse",
  "askpass",
  "afex",
  "blogdown",
  "bookdown",
  "BUCSS",
  "compute.es",
  "cowplot",
  "datapasta",
  "datarium",
  "devtools",
  "DT",
  "easypower",
  "effsize",
  "emmeans",
  "emojifont",
  "faux",
  "ggfortify",
  "ggpubr",
  "ggthemes",
  "here",
  "hrbrthemes",
  "huxtable",
  "jmv",
  "JuliaConnectoR",
  "kableExtra",
  "knitr",
  "komaletter",
  "languageserver",
  "leaflet",
  "learnr",
  "linl",
  "lme4",
  "lmerTest",
  "MBESS",
  "meta",
  "metafor",
  "miniUI",
  "modelbased",
  "MOTE",
  "nlme",
  "pagedown",
  "palmerpenguins",
  "parallelly",
  "PASWR2",
  "pwr",
  "psych",
  "RefManageR",
  "remotes",
  "renv",
  "rmarkdown",
  "Routliers",
  "rpact",
  "simstudy",
  "statcheck",
  "tint",
  "usethis",
  "ufs",
  "vitae",
  "WebPower",
  "weightr",
  "WRS2",
  "xaringan",
  "xaringanthemer"
)

pak::pkg_install(cran_pkgs)

gh_pkgs <- c(
  "arcaldwell49/Superpower",
  "brentthorne/posterdown",
  "crsh/citr",
  "crsh/papaja",
  "crsh/prereg",
  "easystats/easystats",
  "gadenbuie/xaringanExtra",
  "gadenbuie/rsthemes",
  "GRousselet/rogme",
  "hrbrmstr/waffle",
  "Lakens/TOSTER",
  "MathiasHarrer/dmetar",
  "paleolimbot/rbbt",
  "profandyfield/adventr",
  "profandyfield/discovr",
  "ropenscilabs/icon",
  "rstudio/fontawesome",
  "statisfactions/simpr",
  "thomasp85/patchwork"
)

pak::pkg_install(gh_pkgs)

