# R packages for fresh installation

install.packages(c(
  "tidyverse",
  "devtools",
  "remotes",
  "afex",
  "behaviorchange",
  "blogdown",
  "bookdown",
  "broom",
  "BUCSS",
  "cowplot",
  "datarium",
  "DT",
  "easypower",
  "effsize",
  "emmeans",
  "emojifont",
  "faux",
  "gsDesign",
  "here",
  "huxtable",
  "jmv",
  "kableExtra",
  "knitr",
  "komaletter",
  "leaflet",
  "learnr",
  "linl",
  "lme4",
  "MBESS",
  "meta",
  "metafor",
  "miniUI",
  "modelbased",
  "MOTE",
  "pagedown",
  "PASWR2",
  "pwr",
  "psych",
  "RefManageR",
  "renv",
  "rmarkdown",
  "Routliers",
  "rpact",
  "simstudy",
  "statcheck",
  "tint",
  "TOSTER",
  "ufs",
  "vitae",
  "WebPower",
  "weightr",
  "xaringan",
  "xaringanthemer"
))

devtools::install_github("profandyfield/adventr", dependencies = TRUE)
remotes::install_github("profandyfield/discovr")
devtools::install_github("gadenbuie/xaringanExtra")
devtools::install_github("ropenscilabs/icon")
devtools::install_github("MathiasHarrer/dmetar")
remotes::install_github("rstudio/fontawesome")
devtools::install_github("easystats/easystats")
#remotes::install_github("statisfactions/simpr")
#devtools::install_github("gadenbuie/rsthemes")
#devtools::install_github("infotroph/DeLuciatoR") # for ggsave_fitmax
#devtools::install_github("crsh/papaja")
