# R packages for fresh installation

install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")

pak::pkg_install(c(
  "tidyverse",
  "askpass",
  "afex",
  "blogdown",
  "bookdown",
  "broom",
  "BUCSS",
  "cowplot",
  "datarium",
  #"DescTools",
  "devtools",
  "DT",
  "easypower",
  "effsize",
  "emmeans",
  "emojifont",
  "faux",
  "ggfortify",
  "ggpubr",
  "gsDesign",
  "ggthemes",
  "here",
  "hrbrthemes",
  "huxtable",
  "jmv",
  "JuliaConnectoR",
  "kableExtra",
  "knitr",
  "komaletter",
  "leaflet",
  "learnr",
  "linl",
  "lme4",
  "lmerTest",
  "MBESS",
  "meta",
  "metafor",
  "miniUI",
  "modelbased",
  "MOTE",
  "nlme",
  "pagedown",
  "palmerpenguins",
  "PASWR2",
  "pwr",
  "psych",
  "RefManageR",
  "remotes",
  "renv",
  "rmarkdown",
  "Routliers",
  "rpact",
  "simstudy",
  "statcheck",
  "tint",
  "TOSTER",
  "usethis",
  "ufs",
  "vitae",
  "WebPower",
  "weightr",
  "WRS2",
  "xaringan",
  "xaringanthemer"
))

pak::pkg_install("gadenbuie/xaringanExtra")
pak::pkg_install("ropenscilabs/icon")
pak::pkg_install("MathiasHarrer/dmetar")
pak::pkg_install("rstudio/fontawesome")
pak::pkg_install("profandyfield/adventr")
pak::pkg_install("profandyfield/discovr")
pak::pkg_install("crsh/prereg")
pak::pkg_install("GRousselet/rogme")
pak::pkg_install("arcaldwell49/Superpower")
pak::pkg_install("crsh/papaja")
pak::pkg_install("brentthorne/posterdown")
pak::pkg_install("hrbrmstr/waffle")

#pak::pkg_install("easystats/easystats")
#pak::pkg_install("statisfactions/simpr")
#pak::pkg_install("gadenbuie/rsthemes")
#pak::pkg_install("infotroph/DeLuciatoR") # for ggsave_fitmax
